"""Minimal CrystFEL .stream writer for GLINT output -> drops into LUTE / CrystFEL
downstream (cell + per-frame orientation; partialator/CrystFEL predict+integrate from the
astar/bstar/cstar). GLINT indexes (assigns hkl to observed peaks); integration is downstream,
so reflection rows carry h k l and intensity placeholders (fs/ss need detector geometry).

  from fftindex.stream import write_stream
  write_stream([{ "image": "run.cxi", "event": 0, "M": M, "q": q, "hkl": hkl }, ...], "out.stream")
"""
import numpy as np

HEADER = ("CrystFEL stream format 2.3\n"
          "Generated by GLINT (fftindex)\n")


def _cell_block(M):
    M = np.asarray(M, float)
    a, b, c = (np.linalg.norm(M[:, i]) for i in range(3))            # real axes, A
    def ang(i, j):
        u, v = M[:, i], M[:, j]
        return np.degrees(np.arccos(np.clip(u @ v / (np.linalg.norm(u) * np.linalg.norm(v)), -1, 1)))
    Minv = np.linalg.inv(M)                                          # rows = a*,b*,c* in A^-1
    out = ["Begin crystal",
           f"Cell parameters {a/10:.5f} {b/10:.5f} {c/10:.5f} nm, "
           f"{ang(1,2):.3f} {ang(0,2):.3f} {ang(0,1):.3f} deg"]
    for name, v in zip(("astar", "bstar", "cstar"), Minv):
        out.append(f"{name} = {v[0]*10:+.7f} {v[1]*10:+.7f} {v[2]*10:+.7f} nm^-1")
    out += ["lattice_type = triclinic", "centering = P", "unique_axis = *"]
    return "\n".join(out)


def write_stream(results, path):
    """results: list of dicts {image, event, M (3x3 or None), q (N,3), hkl (N,3 int) or None}."""
    n_idx = 0
    with open(path, "w") as f:
        f.write(HEADER)
        for r in results:
            f.write("----- Begin chunk -----\n")
            f.write(f"Image filename: {r.get('image', 'glint.cxi')}\n")
            f.write(f"Event: //{r.get('event', 0)}\n")
            M = r.get("M")
            valid = M is not None and abs(np.linalg.det(np.asarray(M, float))) >= 1.0
            f.write(f"indexed_by = {'glint' if valid else 'none'}\n")
            if valid:
                n_idx += 1
                f.write(_cell_block(M) + "\n")
                f.write("Reflections measured after indexing\n")
                f.write("   h    k    l          I   sigma(I)   peak  background  fs/px  ss/px panel\n")
                hkl = r.get("hkl")
                if hkl is not None:
                    for h, k, l in np.asarray(hkl, int):
                        f.write(f"{h:4d} {k:4d} {l:4d}       0.00      0.00   0.00       0.00    0.0    0.0 p0\n")
                f.write("End of reflections\n")
                f.write("End crystal\n")
            f.write("----- End chunk -----\n")
    return n_idx
